apiVersion: v1
kind: Service
metadata:
  name: theazfront-service
spec:
  type: LoadBalancer
  selector:
    app: theazfront
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000